#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-database_cleaner
Version  : 1.5.3
Release  : 6
URL      : https://rubygems.org/downloads/database_cleaner-1.5.3.gem
Source0  : https://rubygems.org/downloads/database_cleaner-1.5.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec-core

%description
# Database Cleaner
[![Build Status](https://travis-ci.org/DatabaseCleaner/database_cleaner.svg?branch=master)](https://travis-ci.org/DatabaseCleaner/database_cleaner)
[![Code Climate](https://codeclimate.com/github/DatabaseCleaner/database_cleaner/badges/gpa.svg)](https://codeclimate.com/github/DatabaseCleaner/database_cleaner)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n database_cleaner-1.5.3
gem spec %{SOURCE0} -l --ruby > rubygem-database_cleaner.gemspec

%build
export LANG=C
gem build rubygem-database_cleaner.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
database_cleaner-1.5.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/database_cleaner-1.5.3.gem
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/CONTRIBUTE.markdown
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/Gemfile.lock
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/History.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/README.markdown
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/TODO
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/VERSION.yml
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/cucumber.yml
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/Gemfile.lock
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/config/database.yml
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/config/database.yml.example
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/config/redis.yml
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/db/activerecord_one.db
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/db/activerecord_two.db
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/db/datamapper_default.db
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/db/datamapper_one.db
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/db/datamapper_two.db
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/db/sqlite_databases_go_here
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/features/example.feature
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/features/example_multiple_db.feature
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/features/example_multiple_orm.feature
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/features/step_definitions/activerecord_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/features/step_definitions/couchpotato_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/features/step_definitions/datamapper_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/features/step_definitions/mongoid_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/features/step_definitions/mongomapper_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/features/step_definitions/neo4j_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/features/step_definitions/translation_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/lib/activerecord_models.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/lib/couchpotato_models.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/lib/datamapper_models.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/lib/mongoid_models.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/lib/mongomapper_models.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/lib/neo4j_models.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/lib/ohm_models.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/lib/redis_models.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/examples/lib/sequel_models.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/features/cleaning.feature
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/features/cleaning_default_strategy.feature
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/features/cleaning_multiple_dbs.feature
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/features/cleaning_multiple_orms.feature
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/features/step_definitions/database_cleaner_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/features/step_definitions/ohm_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/features/step_definitions/redis_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/features/support/feature_runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/active_record/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/active_record/deletion.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/active_record/transaction.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/active_record/truncation.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/couch_potato/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/couch_potato/truncation.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/cucumber.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/data_mapper/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/data_mapper/transaction.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/data_mapper/truncation.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/generic/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/generic/transaction.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/generic/truncation.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/mongo/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/mongo/truncation.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/mongo/truncation_mixin.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/mongo2/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/mongo2/truncation_mixin.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/mongo_mapper/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/mongo_mapper/truncation.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/mongoid/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/mongoid/truncation.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/moped/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/moped/truncation.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/moped/truncation_base.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/neo4j/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/neo4j/deletion.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/neo4j/transaction.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/neo4j/truncation.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/null_strategy.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/ohm/truncation.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/redis/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/redis/truncation.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/sequel/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/sequel/deletion.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/sequel/transaction.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/sequel/truncation.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/active_record/base_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/active_record/transaction_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/active_record/truncation/mysql2_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/active_record/truncation/mysql_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/active_record/truncation/postgresql_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/active_record/truncation/shared_fast_truncation.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/active_record/truncation/sqlite3_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/active_record/truncation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/base_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/configuration_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/couch_potato/truncation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/data_mapper/base_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/data_mapper/transaction_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/data_mapper/truncation/sqlite3_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/data_mapper/truncation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/generic/base_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/generic/truncation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/mongo/mongo_examples.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/mongo/truncation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/mongo_mapper/base_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/mongo_mapper/mongo_examples.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/mongo_mapper/truncation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/moped/moped_examples.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/moped/truncation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/neo4j/base_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/neo4j/transaction_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/ohm/truncation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/redis/base_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/redis/truncation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/sequel/base_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/sequel/deletion_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/sequel/transaction_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/sequel/truncation/sqlite3_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/sequel/truncation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/database_cleaner/shared_strategy.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/rcov.opts
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/support/active_record/database_setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/support/active_record/migrations/20150101010000_create_users.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/support/active_record/migrations/20150101020000_create_agents.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/support/active_record/mysql2_setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/support/active_record/mysql_setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/support/active_record/postgresql_setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/support/active_record/schema_setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/support/active_record/sqlite3_setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/support/data_mapper/schema_setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/database_cleaner-1.5.3/spec/support/data_mapper/sqlite3_setup.rb
/usr/lib64/ruby/gems/2.3.0/specifications/database_cleaner-1.5.3.gemspec
